---@module 'overseer'

---@mod obazel-nvim.config obazel.nvim configuration
---
---@brief [[
---
---For static task templates, see |obazel.TemplateConfig|. To configure template
---generators see |obazel.GeneratorConfig|. No templates are defined by default.
---
---------------------------------------------------------------------------------
---Example configuration
--->lua
---     ---@module 'obazel'
---     require("obazel").setup({
---       -- (optional) The binary used to invoke bazel commands
---       bazel_binary = "bazel",
---       overseer = {
---         -- static task templates
---         templates = {
---           {
---             args = { "run", "//:gazelle" },
---             template = { name = "bazel run //:gazelle" },
---           },
---         },
---         -- task templates generated via bazel queries
---         generators = {
---           {
---             query_template = "tests(%s:*)",
---             args = { "test" },
---             template_file_definition = {
---               tags = { "TEST" },
---             },
---           },
---           {
---             query_template = 'kind(".*_binary", %s:*)',
---             args = { "run" },
---             template_file_definition = {
---               tags = { "RUN" },
---             },
---           },
---           {
---             query_template = "kind(rule, %s:*)",
---             args = { "build" },
---             template_file_definition = {
---               tags = { "BUILD" },
---             },
---           },
---         },
---       },
---     })
---
---Because |obazel.setup()| passes the config directly as a Lua table, values
---like `template_file_definition` or `template` may contain overseer
---components with configuration options, e.g.
---`{ "on_output_parse", errorformat = "..." }`. This wasn't possible with the
---old `vim.g.obazel`-based configuration, since values assigned to `vim.g`
---variables are round-tripped through Vimscript, which has no way to
---represent that shape of table.
---
---@brief ]]

---@class obazel.Config
---@field bazel_binary? string (optional) (default: "bazel")
---@field overseer? obazel.OverseerConfig (optional)

---@class obazel.OverseerConfig
---@field templates? obazel.TemplateConfig[] (optional) static task templates
---@field generators? obazel.GeneratorConfig[] (optional) bazel query based template generators

---A static template definition for bazel targets that you always want to have
---available. For example `bazel run //:gazelle`.
---
---Use the `template` argument to set the `name` of the task:
--->lua
---     {
---         args = { "run", "//:gazelle" },
---         template = { name = "bazel run //:gazelle" },
---     }
---@class obazel.TemplateConfig
---@field args? string[] (optional) the args that will be passed to bazel; omit for none, e.g. `binary target`
---@field after_target_args? string[] (optional) args appended after `args`, e.g. for flags to pass through to the target itself via `--`
---@field binary? string (optional) override the configured `bazel_binary` for this template
---@field cwd? string|fun(workspace_root: string): string (optional) task working directory, or a function of the resolved bazel workspace root that returns one; defaults to the workspace root
---@field env? table<string, string> (optional) environment variables for the task
---@field metadata? table (optional) arbitrary metadata for the task
---@field components? overseer.Serialized[] (optional) overseer components for the task
---@field relative_file_root? string|fun(workspace_root: string): string (optional) root for resolving relative paths reported by output-parsing components (e.g. compiler diagnostics), or a function of the resolved bazel workspace root that returns one; defaults to the workspace root. Unlike overseer's own `relative_file_root` param, this does *not* fall back to task `cwd` when unset: bazel's own diagnostics are reported relative to the workspace root regardless of `cwd`, so obazel pins this independently rather than letting it silently track a `cwd` override.
---@field template overseer.TemplateDefinition the template definition

---A template generator using a bazel query.
---
---The query_template should be a string that contains '%s' which will be
---replaced with the resolved `target_prefix` for the file in the current
---buffer. The `target_prefix` is resolved using
---|obazel-nvim.bazel.resolve_target_prefix|.
---
---Use the `template_file_definition` to override values in the base template:
--->lua
---     {
---       query_template = "tests(%s:*)",
---       args = { "test" },
---       template_file_definition = {
---         tags = { "TEST" },
---       },
---     }
---@class obazel.GeneratorConfig
---@field query_template string a query template where '%s' will be replaced by the target_prefix
---@field args? string[] (optional) args that will be passed to bazel before the targets; omit for none, e.g. `binary target`
---@field after_target_args? string[] (optional) args appended after the resolved target, e.g. for flags to pass through to the target itself via `--`
---@field binary? string (optional) override the configured `bazel_binary` for generated tasks
---@field cwd? string|fun(workspace_root: string): string (optional) task working directory, or a function of the resolved bazel workspace root that returns one; defaults to the workspace root
---@field env? table<string, string> (optional) environment variables for generated tasks
---@field metadata? table (optional) arbitrary metadata for generated tasks
---@field components? overseer.Serialized[] (optional) overseer components for generated tasks
---@field relative_file_root? string|fun(workspace_root: string): string (optional) root for resolving relative paths reported by output-parsing components (e.g. compiler diagnostics), or a function of the resolved bazel workspace root that returns one; defaults to the workspace root. Unlike overseer's own `relative_file_root` param, this does *not* fall back to task `cwd` when unset: bazel's own diagnostics are reported relative to the workspace root regardless of `cwd`, so obazel pins this independently rather than letting it silently track a `cwd` override.
---@field template_file_definition? table (optional) overrides values in the base overseer.TemplateFileDefinition
---@see overseer.TemplateFileDefinition

local config = {}

return config
