name: Lint
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nebularg/actions-luacheck@v1.1.2
        with:
          files: 'lua/ plugin/ spec/'
          config: 'https://github.com/glindstedt/obazel.nvim/blob/main/.luacheckrc'
          annotate: 'error'
