name: LuaRocks realase
on:
  push:
    tags:
      - "*"
  workflow_dispatch: # Allows manual triggering
  pull_request: # Will test a local install without uploading to luarocks.org

jobs:
  luarocks-upload:
    runs-on: ubuntu-latest
    name: LuaRocks upload
    steps:
      - uses: actions/checkout@v4
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          test_dependencies: |
            nlua
